### ISSUE TITLE
`exit` or `ctrl-d` closes the whole k3rmit window, instead of just closing the tab

### ISSUE THREAD

**Issue by BlitzKraft** [KeyLo99/k3rmit#3]
That would be expected behaviour if there is only one tab open. Possibly there needs to be a check when there are multiple tabs open?

**Comment by KeyLo99** [comment]
It's a known bug caused by the `child-exited` signal. Actually there's already a check for it in the code and it's expected to close tab without terminal exit.
So, I need you to provide more information about bug (OS, key binding etc.)
And I'll improve that check ASAP.

**Comment by BlitzKraft** [comment]
OS is sabayon linux. Using bspwm. I used both exit and ctrl-D. Both tested with 2 open tabs. I didn't use any other keybindings. This was done fresh after compile (from master). I didn't install it yet. 

Let me know if you want any further details.

**Comment by KeyLo99** [comment]
Okay, I'm trying the understand the cause of the problem. 
I've changed the check a little bit, can you compile and try it again and post results? (218cac4327745ea008b1bd30797c84bc483b4302)

**Comment by BlitzKraft** [comment]
I tried the latest commit. Hitting ctrl-d types "exit" and hangs. The tab still persists. When I type out exit, another "exit" is printed and hangs.

**Comment by KeyLo99** [comment]
Okay I think I got the problem. But I have to know what your tab count is before the exit. 
Adding this code to #L122 and posting the output would help me a lot actually.
```
fprintf(stderr, "%d -", gtk_notebook_get_n_pages(GTK_NOTEBOOK(notebook)));
```

**Comment by KeyLo99** [comment]
And I've checked again and `ctrl-d` or `exit` command closing the whole window is an expected behaviour according to my code. (v1.2)
But I'm going to fix this anyway.

**Comment by BlitzKraft** [comment]
I tried closing with two tabs and 4 tabs. With the same result. I tried exiting all tabs, but they all hang up together. I have Alt-F4 the window to close it. 

When I have just one tab, both ctrl-d and exit close the k3 window entirely.

**Comment by KeyLo99** [comment]
Okay, hope that a4862a76ef0fd464a1681701d3a8ff2b571a3218 will solve the issue.

**Comment by BlitzKraft** [comment]
Nice!! Fixes everything!  Closing. 

On a side note, could you add how to specify fonts? I tried a few things and they didn't set the correct font.

**Comment by KeyLo99** [comment]
Yeah of course! I will probably do that later.

**Comment by KeyLo99** [comment]
Font specification information added to repository: https://github.com/KeyLo99/k3rmit#font
